SDK Init
gandalf-network/connect pull request #1
Opened 2024-02-21 11:51 UTC by TosinJs

## Description

- Generate App Clip URL
- Generate QR Code

Updated Video

https://www.loom.com/share/5f39611464954fc491da8884ab242b16

https://www.loom.com/share/3f9f1c70fb434888ae7d123ffa14a11d

## Motivation and Context

## How Has This Been Tested?

**Screen recording (compulsory)**:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Improvement (general improvements to how code looks/works)

## Checklist

- [ ] I have created a branch for this patch/feature.
- [ ] My pull request addresses exactly one patch/feature.
- [ ] Each individual commit in the pull request is meaningful.
- [ ] I have tested manually on my deployed review app.
- [ ] My code follows the code style of this project.

- [ ] I have requested and received approval from a peer
- [ ] I have requested and received (initial) approval from the code owner
- [ ] I have completed QA testing
- [ ] I have received final approval from the code owner

2024-02-21 13:08 UTC, TheDhejavu commented on src/lib/request.ts
> +export const gql_request = async (
this should be camelCase

2024-02-21 15:02 UTC, timigod requested changes

2024-02-21 15:02 UTC, timigod commented on examples/example.ts
> +const redirectURL = "https://medium.com/bynder-tech/creating-a-sdk-from-scratch-2809ded9fa8a"
<img width="498" alt="image" src="https://github.com/gandalf-network/connect-client-sdk/assets/8492819/cf345e7f-7303-44b6-a362-77a722585034">

The redirect URL seems clipped, except maybe your demo video has a different thing. I also think that maybe we should validate (and/or remove trailing slashes at the end of the URL)

2024-02-21 15:02 UTC, timigod commented on src/lib/constants.ts
> +export const APP_CLIP_BASE_URL = process.env.APP_CLIP_BASE_URL as string;
How will this be set in practice? It should probably be a part of the CI/CD build step no? And eventually be bundled/hardcoded as part of the library (vs the developer having to set an env var or anything of the sort).

2024-02-21 15:02 UTC, timigod commented on src/connect.ts
> +export enum SupportedServices {
Hmm, not sure that this shouldn't be automated/not hardcoded. Options:

- Make API call to get list of supported services (we'll have that enum somewhere in the graphql, so you can either create a new query or just check the types from the schema via introspection). The downside of this is that it makes the API slower.

- It could also be a build step for the library, downside is that if we don't push a new version, then devs won't have access to newly supported services.

- We could do something similar to what I'm suggesting with the server-side library such that devs have a command to refresh/generate these stuff from schema sha. 

What do you think?

2024-02-21 15:05 UTC, TosinJs commented on examples/example.ts
> +const redirectURL = "https://medium.com/bynder-tech/creating-a-sdk-from-scratch-2809ded9fa8a"
Yeah, the demo app is different, I shortened it. I'll remove the trailing slashes.

2024-02-21 15:06 UTC, TosinJs commented on src/lib/constants.ts
> +export const APP_CLIP_BASE_URL = process.env.APP_CLIP_BASE_URL as string;
Yes, this will be bundled as part of the SDK with webpack, the setup for this is here: https://github.com/gandalf-network/connect-client-sdk/blob/e8e41baa2a71450b39ab393e50e80849480679c9/webpack.config.js

2024-02-21 15:46 UTC, TosinJs commented on src/connect.ts
> +export enum SupportedServices {
I think the generate function or the post install script is fine, it should definitely not be hardcoded.

Although the generate function approach puts some extra duty on the devs to keep their local and production environments in sync.

2024-02-21 19:04 UTC, sa-ma requested changes

2024-02-21 19:04 UTC, sa-ma commented on examples/example.ts
> +const redirectURL = "https://medium.com/bynder-tech/creating-a-sdk-from-scratch-2809ded9fa8a"
Please also encode the URL

2024-02-21 19:04 UTC, sa-ma commented on examples/example.ts
> +    const qrCode = await connect.outputQRCode()
I think `connect.generateQRCode` is better

2024-02-21 19:04 UTC, sa-ma commented on src/connect.ts
> +	}
There should be a check to make sure the user doesn't pass only one service as an optional service i.e `{netflix: false}` should throw an error

2024-02-21 19:04 UTC, sa-ma commented on src/lib/request.ts
> +import { gql, GraphQLClient } from 'graphql-request';
You should use `graphql-codegen` to make sure the queries and mutations are typed

2024-02-21 19:04 UTC, sa-ma commented on src/tests/connect.spec.ts
> +
Please add a test case to make sure the SDK throws an error if a user passes only one service as an optional service

2024-02-22 08:57 UTC, timigod requested changes
The developer should not have to `cd` into the project (via their node_modules folder) to regenerate the schema. We should add an easy to use command line command that they can just run once they have our module installed. 

The command shouldn't be "generate-gql" either, the entire point of this is to abstract all of that knowledge of GQL from the developer. It could be something like `update-services`, or just `update` , maybe `gandalf update` or something. 

The QR code is still wonky btw. I think @enipx is still struggling with this. What's the status on that Hashir? Especially considering that you've moved on to the landing page, did you fix it?

2024-02-22 08:57 UTC, timigod commented on src/connect.ts
> +			throw new Error(`These services ${unsupportedServices.join(' ')} are unsupported`)
@TosinJs not sure I'm satisfied with the way we're throwing errors - as just strings. We should likely define custom error classes with codes (not necessarily integer codes, but they could be string codes like VALIDATION_ERROR) that are easier for devs to catch & do stuff conditionally based on.

2024-02-23 00:14 UTC, timigod requested changes

2024-02-23 00:14 UTC, timigod commented on codegen.ts
> +            ["https://watson-v2-staging.onrender.com/gql"]: {},
@TosinJs this shouldn't be hardcoded, no? We don't want to hardcode a staging URL in the library permanently.

2024-02-23 00:14 UTC, timigod commented on src/lib/errors.ts
> +class ConnectError extends Error {
I'm leaning towards `GandalfError`, connect seems like it could be anything - make the dev no go dey check their DB connection or whatever, wdyt?

2024-02-23 00:14 UTC, timigod commented on src/lib/qrCode-style.ts
> +        data: "https://qr-code-styling.com",
This looks like a mistake, no?

2024-02-23 03:16 UTC, TosinJs commented on src/lib/qrCode-style.ts
> +        data: "https://qr-code-styling.com",
Yes. it was supposed to be the url.

2024-02-23 10:41 UTC, timigod approved these changes

2024-02-23 10:43 UTC, merged